Repository Ant-Shell/tainted-peaches, pull requests merged in 2022-08, with the labels that each got.

#8 Restructuring / initial commits
  src/App.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/MovieCardsCollection/MovieCardsCollection.css
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/index.js
Labels: enhancement

#9 Component/nav
  src/assets/tainted-peach.jpeg
  src/assets/tainted.jpeg
  src/components/App/App.js
  src/components/Footer/Footer.js
  src/components/MovieCard/Moviecard.css
  src/components/MovieCard/Moviecard.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
Labels: enhancement, Iteration 1

#10 Component/movie card
  src/components/App/App.js
  src/components/MovieCard/Moviecard.js
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/fakedata.js
Labels: enhancement, Iteration 1

#11 Styling iteration 1 css
  package-lock.json
  public/index.html
  src/assets/cinema-background.jpg
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/MovieCard/Moviecard.css
  src/components/MovieCard/Moviecard.js
  src/components/MovieCardsCollection/MovieCardsCollection.css
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/index.css
Labels: enhancement, Iteration 1

#13 Feature/fetch api data
  src/apiCalls.js
  src/assets/github.png
  src/assets/linkedin.png
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/MovieCard/Moviecard.css
  src/components/MovieCard/Moviecard.js
  src/components/MovieCardsCollection/MovieCardsCollection.css
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/fakedata.js
Labels: enhancement, Iteration 3

#14 Feature/displaying single movie details
  src/apiCalls.js
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/MovieCard/Moviecard.js
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement, iteration 2

#15 Feature/temporary home button
  src/components/App/App.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/Nav/Nav.js
Labels: iteration 2

#16 Css styling of movie details
  src/apiCalls.js
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.js
Labels: enhancement, iteration 2

#17 Refactor/css refactoring
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement

#18 Feature/router
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.js
  src/index.js
Labels: enhancement

#19 Feature/cypress
  cypress.config.js
  cypress/e2e/movie_cards_collection.cy.js
  cypress/e2e/movie_details.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: enhancement, Iteration 3

#20 Refactor router to function properly
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.js
  src/index.js
Labels: enhancement, Iteration 4

#21 Refactor/css refactoring
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/index.js
Labels: enhancement
