Repository Ant-Shell/tainted-peaches, pull requests merged in 2022-09, with the labels that each got.

#24 Testing/more cypress testing
  cypress/e2e/movie_cards_collection.cy.js
  cypress/e2e/movie_details.cy.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement

#25 Testing/updating cypress test
  cypress/e2e/movie_cards_collection.cy.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Footer/Footer.css
  src/components/MovieCardsCollection/MovieCardsCollection.css
  src/components/MovieDetails/MovieDetails.css
  src/components/Nav/Nav.css
Labels: enhancement

#26 Fixed bug where home button didn't re-render
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.js
  src/index.css
Labels: bug, Iteration 4

#27 Fixing cypress tests
  cypress/e2e/movie_cards_collection.cy.js
  cypress/e2e/movie_details.cy.js
  src/components/Footer/Footer.css
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.css
Labels: bug, Iteration 4

#31 Documentation/readme
  README.md
  cypress/e2e/movie_cards_collection.cy.js
  cypress/e2e/movie_details.cy.js
  public/index.html
  src/apiCalls.js
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/MovieCardsCollection/MovieCardsCollection.css
  src/components/MovieCardsCollection/MovieCardsCollection.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/index.css
  src/index.js
  src/logo.svg
Labels: documentation

#32 Experimental/app deploy
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.js
  src/components/Nav/Nav.js
Labels: bug, Iteration 5
